networks:
  app-tier:
    driver: bridge

services:
  elasticsearch:
    image: bitnami/elasticsearch:8.13.4
    container_name: elasticsearch
    networks:
      - app-tier
    volumes:
      - 'd:\elasticsearch:/bitnami/elasticsearch/data'
    ports:
     - "9400:9200"

  kibana:
    image: bitnami/kibana:8.13.4
    container_name: kibana
    environment:
      - KIBANA_ELASTICSEARCH_PORT_NUMBER=9400
      - KIBANA_PORT_NUMBER=5601
    networks:
      - app-tier
    volumes:
      - 'd:\kibana:/bitnami/kibana'
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  kafka:
   image: 'bitnami/kafka:3.7.0'
   container_name: kafkaserver
   hostname: kafkaserver
   networks:
    - app-tier
   ports:
    - "9092:9092"
    - "9094:9094"
   volumes:
    - "kafka_data:/bitnami"
   environment:
    - KAFKA_CFG_NODE_ID=1001
    - KAFKA_CFG_PROCESS_ROLES=controller,broker
    - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
    - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
    - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1001@kafka:9093
    - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT

volumes:
  kafka_data:
    driver: local