networks:
  app-tier:
    driver: bridge

services:
  elasticsearch:
    image: bitnami/elasticsearch:8.13.4
    container_name: elasticsearch
    networks:
      - app-tier
    volumes:
      - 'd:\elasticsearch:/bitnami/elasticsearch/data'
    ports:
     - "9400:9200"

  kibana:
    image: bitnami/kibana:8.13.4
    container_name: kibana
    environment:
      - KIBANA_ELASTICSEARCH_PORT_NUMBER=9400
      - KIBANA_PORT_NUMBER=5601
    networks:
      - app-tier
    volumes:
      - 'd:\kibana:/bitnami/kibana'
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
