spring:
 application:
  name: email-sender

 data:
  elasticsearch:
    repositories:
      enabled: true

 kafka:
  bootstrap-servers: localhost:9094
  group-id: consumer-group
  number-of-partitions: 1
  replication-factor: 1

 mail:
  host: smtp.gmail.com
  port: 587
  properties:
    mail:
      debug: true
      transport:
        protocol: smtp
      smtp:
        auth: true
        starttls:
          enable: true

server:
  servlet:
    context-path: /library
  port: 8090
  error:
    whitelabel:
      enabled: false
    include-stacktrace: never
    include-message: never

debug: true
logging:
  level:
    '[com.streamlined.emailsender.EmailSenderApplication]': TRACE
    org:
      springframework:
        security: TRACE
        web:
          FilterChainProxy: TRACE
