spring:
 application:
  name: email-sender

 config:
    import:
    - optional:file:.env[.properties]

 data:
  elasticsearch:
    repositories:
      enabled: true

 kafka:
  bootstrap-servers: localhost:9094
  topic: notification
  number-of-partitions: 1
  replication-factor: 1
  consumer:
   group-id: consumer-group

 mail:
  properties:
    mail:
      debug: true
      transport:
        protocol: smtp
      smtp:
        auth: true
        starttls:
          enable: true

server:
  port: 8090
  error:
    whitelabel:
      enabled: false
    include-stacktrace: never
    include-message: never

debug: true
logging:
  level:
    '[com.streamlined.emailsender.EmailSenderApplication]': TRACE
    org:
      springframework:
        security: TRACE
        web:
          FilterChainProxy: TRACE
